database: hsqldb

amadeus:
  apiKey: 0IY3aBOHlysqRnLdxmJpWnZ5CjUrr2Vf
  apiSecret: D9XiaCmaKsgecobJ
# Database Settings
spring:

  datasource:
      schema: classpath*:/${database}/schema.sql
      data: classpath*:/${database}/data.sql
      url: jdbc:h2:mem:testdb;MODE=mysql;
      platform: h2
      username: sa
      password:
      driverClassName: org.h2.Driver

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: false
